// lang.js

const translations = {
  en: {
    navHome: "Home",
    navActivities: "Activities",
    navBooking: "Booking",
    navAuth: "Login / Register",
    langSwitch: "TH",
    footerDesc: "Experience exciting ocean adventures with our unique activities.",
    serviceBtn: "Book this activity",
    activityHeader: "Our Available Activities",
    activityDescription: "Choose your type of activity to experience an unforgettable adventure.",
    titleDive: "Scuba Diving Course",
    descDive: "Learn scuba diving with our experienced professional team. Explore the underwater world safely and enjoyably.",
    perPerson: "person",
    btnScuba: "View Details",
    titleSnorkel: "Snorkeling",
    descSnorkel: "Enjoy shallow water coral reefs and colorful fish. Perfect for beginners and families.",
    perSession: "person",
    btnSnorkel: "View Details",
    titleSki: "Jetski Riding",
    descSki: "Enjoy jetskiing in the sea with stunning views and modern, safe equipment.",
    perHour: "day",
    btnSki: "View Details",
    titleBoat: "Private Boat Rental",
    descBoat: "Choose a boat suited for your journey with scenic routes or diving spots.",
    perDay: "day",
    btnBoat: "View Details",
    boatDesc: "Choose a boat for your special trip — sightseeing, diving, or private parties.",
    boatIncludeTitle: "✅ Included:",
    boatInclude1: "Boat with captain",
    boatInclude2: "Drinking water and life jackets",
    boatInclude3: "Route guidance service",
    boatDurationTitle: "🕒 Duration:",
    boatDuration: "Full day (up to 8 hours)",
    boatNoteTitle: "📌 Note:",
    boatNote1: "Book at least 1 day in advance",
    boatNote2: "Max 10 passengers",
    boatPrice: "Price: ฿5,000 / day",
    authPageTitle: "Register / Login",
    toggleRegister: "Register",
    toggleLogin: "Login",
    registerTitle: "Register",
    regUsernameLabel: "Username:",
    regPasswordLabel: "Password:",
    regConfirmLabel: "Confirm Password:",
    registerBtn: "Register",
    loginTitle: "Login",
    loginUsernameLabel: "Username:",
    loginPasswordLabel: "Password:",
    loginBtn: "Login",
    footerAuthDesc: "Experience the ultimate marine adventures with our exciting sea activities.", // แยก footer สำหรับหน้า Auth
    bookingTitle: "Book an Activity with Us",
    labelName: "Full Name",
    inputName: "Enter your name",
    labelEmail: "Email",
    inputEmail: "your@email.com",
    labelActivity: "Choose Activity",
    labelPeople: "Number of People",
    inputPeople: "Enter number of people",
    labelDate: "Booking Date",
    submitBtn: "Confirm Booking",
    activitySelect: "-- Please Select --",
    scuba: "Scuba Diving Course",
    snorkeling: "Snorkeling",
    boat: "Private Boat Rental",
    jetski: "Jet Ski Ride",
    paymentTitle: "Payment",
    paymentMethodLabel: "Select Payment Method:",
    optionCard: "Credit/Debit Card",
    optionQR: "QR Code",
    nextBtn: "Next",
    cardTitle: "Pay with Credit Card",
    submitCard: "Pay with Card",
    qrTitle: "Pay via QR Code",
    qrInstruction: "Scan the QR code below to complete your payment",
    scubaDesc:
      "Our scuba diving course is designed for beginners looking to explore the underwater world safely.\nYou will learn how to use scuba gear, breathe underwater, control your buoyancy, and use hand signals\nunder the guidance of certified professional instructors.",
    scubaIncludeTitle: "✅ Course includes:",
    scubaInclude1: "Introductory theory training",
    scubaInclude2: "Full set of scuba gear",
    scubaInclude3: "2 dives with instructor",
    scubaInclude4: "Underwater photography",
    scubaDurationTitle: "🕒 Duration:",
    scubaDuration: "Half-day (approximately 4 hours)",
    scubaNoteTitle: "📌 Note:",
    scubaNote1: "Suitable for ages 12 and up",
    scubaNote2: "Get enough rest before joining the activity",
    scubaNote3: "Not suitable for people with severe heart or asthma conditions",
    scubaPrice: "Price: ฿3,500 / person",
    snorkelDesc: "Explore the shallow coral reefs — perfect for all ages and experience levels.",
    snorkelIncludeTitle: "✅ Includes:",
    snorkelInclude1: "Mask, life vest, and snorkel",
    snorkelInclude2: "Experienced guide",
    snorkelInclude3: "Boat transport to dive site",
    snorkelDurationTitle: "🕒 Duration:",
    snorkelDuration: "2 hours",
    snorkelNoteTitle: "📌 Notes:",
    snorkelNote1: "Suitable for all ages",
    snorkelNote2: "Non-swimmers are welcome",
    snorkelPrice: "Price: ฿1,200 / person",
    thankYouTitle: "Thank you for your booking!",
    thankYouMessage: "Your booking has been completed and payment has been received.",
    bookingDetailTitle: "Booking Details",
    labelService: "Service:",
    labelDate: "Date:",
    labelTime: "Time:",
    labelPeople: "People:",
    labelPrice: "Total Price:",
    currency: "Baht",
    backHomeBtn: "Back to Home",
    head: "Aquaventure",
    heroTitle: "Discover fun in every adventure!",
    heroDesc: "Make every day exciting at Aquaventure — dive, sail, or jetski with a smile!",
    heroBtn: "Start Your Adventure",
    servicesTitle: "Our Services",
    divingTitle: "Scuba Diving",
    divingDesc: "Experience the magical underwater world...",
    snorkelingTitle: "Snorkeling",
    snorkelingDesc: "Relax and enjoy snorkeling through coral reefs...",
    boatingTitle: "Boat Trip",
    boatingDesc: "Enjoy a scenic boat ride...",
    jetskiTitle: "Jet Ski",
    jetskiDesc: "Feel the thrill of high-speed jet skiing!",
    ctaTitle: "Ready for your next adventure?",
    ctaDesc: "Sign up or log in to get started",
    ctaBtn: "Register or Login",

    divingDetailBtn: "View Details",
    snorkelingDetailBtn: "View Details",
    boatingDetailBtn: "View Details",
    jetskiDetailBtn: "View Details",

    titleJetski: "Jetski Ride",
    jetskiDesc: "Get thrilled riding a jetski across the sparkling sea while enjoying the bay view.",
    
    jetskiIncludeTitle: "✅ Included:",
    jetskiInclude1: "1 jetski per 2 people",
    jetskiInclude2: "Life jacket",
    jetskiInclude3: "Guidance from staff",
    
    jetskiDurationTitle: "🕒 Duration:",
    jetskiDuration: "1 hour",

    jetskiNoteTitle: "📌 Note:",
    jetskiNote1: "Must be at least 15 years old",
    jetskiNote2: "No license required",

    jetskiPrice: "Price: ฿2,000 / hour",
    serviceBtn: "Book This Activity",
    pageTitle: "Aquaventure - Booking",
    logoText: "Aquaventure",
    navHome: "Home",
    navActivities: "Activities",
    bookingTitle: "Book Your Adventure",
    labelName: "Full Name",
    inputName: "Enter your name",
    labelEmail: "Email",
    labelActivity: "Choose Activity",
    activityOptionDefault: "-- Please select an activity --",
    activityOptionScuba: "Scuba Diving Course",
    activityOptionSnorkeling: "Snorkeling",
    activityOptionBoat: "Private Boat Rental",
    activityOptionJetski: "Jet Ski Ride",
    labelPeople: "Number of People",
    inputPeople: "Enter number of people",
    labelDate: "Booking Date",
    submitBtn: "Confirm Booking",
    footerTitle: "Aquaventure",
    footerDesc: "Experience thrilling ocean adventures with us.",
    footerCopyright: "© 2025 Aquaventure Adventures",
    activityOptionScuba: "Scuba Diving Course",        // en
    activityOptionSnorkeling: "Snorkeling",
    activityOptionBoat: "Private Boat Rental",
    activityOptionJetski: "jetski",
    labelTime: "Preferred Time",
        
  },
  th: {
    navHome: "หน้าแรก",
    navActivities: "กิจกรรม",
    navBooking: "การจอง",
    navAuth: "เข้าสู่ระบบ / สมัครสมาชิก",
    langSwitch: "EN",
    footerDesc: "สัมผัสประสบการณ์การผจญภัยสุดพิเศษกับกิจกรรมทางทะเลที่น่าตื่นเต้น",
    serviceBtn: "จองกิจกรรมนี้",
    activityHeader: "กิจกรรมที่เรามีให้บริการ",
    activityDescription: "เลือกรูปแบบกิจกรรมที่คุณต้องการสัมผัส ประสบการณ์ที่น่าตื่นเต้นและไม่มีวันลืม",
    titleDive: "คอร์สดำน้ำ Scuba",
    descDive: "เรียนรู้การดำน้ำกับทีมงานมืออาชีพที่มีประสบการณ์ พิชิตโลกใต้ทะเลกับกิจกรรมที่ปลอดภัยและสนุกสนาน",
    perPerson: "ท่าน",
    btnScuba: "ดูรายละเอียด",
    titleSnorkel: "ดำน้ำตื้น",
    descSnorkel: "เพลิดเพลินกับโลกใต้น้ำตื้นๆ ที่เต็มไปด้วยปะการังและฝูงปลาสีสันสดใส เหมาะสำหรับผู้เริ่มต้นและครอบครัว",
    perSession: "ท่าน",
    btnSnorkel: "ดูรายละเอียด",
    titleSki: "ขับเจ็ทสกี",
    descSki: "สนุกกับการเล่นเจ็ทสกีบนทะเลพร้อมวิวทิวทัศน์ที่สวยงามสุดๆ นอกจากนี้ยังมีอุปกรณ์ที่ทันสมัยและปลอดภัย",
    perHour: "วัน",
    btnSki: "ดูรายละเอียด",
    titleBoat: "เช่าเรือส่วนตัว",
    descBoat: "เลือกเรือที่เหมาะกับการท่องเที่ยวของคุณ พร้อมกับเส้นทางชมทิวทัศน์หรือการดำน้ำตามจุดที่น่าสนใจ",
    perDay: "วัน",
    btnBoat: "ดูรายละเอียด",
    boatDesc: "เลือกเรือสำหรับทริปพิเศษ ไม่ว่าจะล่องชมวิว ดำน้ำ หรืองานเลี้ยงส่วนตัว",
    boatIncludeTitle: "✅ สิ่งที่รวม:",
    boatInclude1: "เรือพร้อมคนขับ",
    boatInclude2: "น้ำดื่ม และเสื้อชูชีพ",
    boatInclude3: "บริการแนะนำเส้นทาง",
    boatDurationTitle: "🕒 ระยะเวลา:",
    boatDuration: "เต็มวัน (สูงสุด 8 ชั่วโมง)",
    boatNoteTitle: "📌 หมายเหตุ:",
    boatNote1: "จองล่วงหน้าอย่างน้อย 1 วัน",
    boatNote2: "รองรับผู้โดยสารไม่เกิน 10 คน",
    boatPrice: "ราคา: ฿5,000 / วัน",
    authPageTitle: "สมัครสมาชิก / ล็อกอิน",
    toggleRegister: "สมัครสมาชิก",
    toggleLogin: "ล็อกอิน",
    registerTitle: "สมัครสมาชิก",
    regUsernameLabel: "ชื่อผู้ใช้:",
    regPasswordLabel: "รหัสผ่าน:",
    regConfirmLabel: "ยืนยันรหัสผ่าน:",
    registerBtn: "สมัครสมาชิก",
    loginTitle: "ล็อกอิน",
    loginUsernameLabel: "ชื่อผู้ใช้:",
    loginPasswordLabel: "รหัสผ่าน:",
    loginBtn: "ล็อกอิน",
    footerAuthDesc: "สัมผัสประสบการณ์การผจญภัยสุดพิเศษกับกิจกรรมทางทะเลที่น่าตื่นเต้น", 
    bookingTitle: "จองกิจกรรมกับเรา",
    labelName: "ชื่อ - นามสกุล",
    inputName: "กรอกชื่อของคุณ",
    labelEmail: "อีเมล",
    inputEmail: "your@email.com",
    labelActivity: "เลือกกิจกรรม",
    labelPeople: "จำนวนคน",
    inputPeople: "ระบุจำนวนคน",
    labelDate: "วันที่ต้องการจอง",
    submitBtn: "ยืนยันการจอง",
    activitySelect: "-- กรุณาเลือก --",
    scuba: "คอร์สดำน้ำ Scuba",
    snorkeling: "ดำน้ำตื้น",
    boat: "เช่าเรือส่วนตัว",
    jetski: "ขับเจ็ทสกี",
    paymentTitle: "การชำระเงิน",
    paymentMethodLabel: "เลือกวิธีการชำระเงิน:",
    optionCard: "บัตรเครดิต/เดบิต",
    optionQR: "QR Code",
    nextBtn: "ถัดไป",
    cardTitle: "การชำระเงินผ่านบัตรเครดิต",
    submitCard: "ชำระเงินผ่านบัตรเครดิต",
    qrTitle: "การชำระเงินผ่าน QR Code",
    qrInstruction: "สแกน QR Code ด้านล่างเพื่อทำการชำระเงิน",
    scubaDesc:
      "คอร์สดำน้ำ Scuba ของเราถูกออกแบบมาเพื่อผู้ที่ต้องการเริ่มต้นการผจญภัยใต้น้ำอย่างปลอดภัย\nคุณจะได้เรียนรู้พื้นฐานการใช้อุปกรณ์ การหายใจใต้น้ำ การลอยตัว และสัญญาณมือ\nโดยมีครูฝึกที่ผ่านการรับรองจากองค์กรระดับโลกดูแลตลอดเวลา",
    scubaIncludeTitle: "✅ สิ่งที่รวมอยู่ในคอร์ส:",
    scubaInclude1: "การฝึกภาคทฤษฎีเบื้องต้น",
    scubaInclude2: "อุปกรณ์ดำน้ำครบชุด",
    scubaInclude3: "ดำน้ำ 2 ไดฟ์พร้อมครูผู้สอน",
    scubaInclude4: "ภาพถ่ายใต้น้ำ",
    scubaDurationTitle: "🕒 ระยะเวลา:",
    scubaDuration: "ครึ่งวัน (ประมาณ 4 ชั่วโมง)",
    scubaNoteTitle: "📌 หมายเหตุ:",
    scubaNote1: "เหมาะสำหรับอายุ 12 ปีขึ้นไป",
    scubaNote2: "ควรพักผ่อนให้เพียงพอก่อนร่วมกิจกรรม",
    scubaNote3: "ไม่เหมาะกับผู้มีโรคหัวใจหรือหอบหืดรุนแรง",
    scubaPrice: "ราคา: ฿3,500 / ท่าน",
    snorkelDesc: "สำรวจโลกใต้ทะเลในแนวปะการังตื้น ๆ เหมาะสำหรับทุกเพศทุกวัย",
    snorkelIncludeTitle: "✅ สิ่งที่รวม:",
    snorkelInclude1: "หน้ากากดำน้ำ เสื้อชูชีพ ท่อหายใจ",
    snorkelInclude2: "ไกด์ผู้เชี่ยวชาญ",
    snorkelInclude3: "เรือรับส่งถึงจุดดำน้ำ",
    snorkelDurationTitle: "🕒 ระยะเวลา:",
    snorkelDuration: "2 ชั่วโมง",
    snorkelNoteTitle: "📌 หมายเหตุ:",
    snorkelNote1: "เหมาะกับทุกวัย",
    snorkelNote2: "ผู้ที่ว่ายน้ำไม่เป็นสามารถร่วมได้",
    snorkelPrice: "ราคา: ฿1,200 / ท่าน",
    thankYouTitle: "ขอบคุณสำหรับการจองของคุณ!",
    thankYouMessage: "การจองของคุณเสร็จสมบูรณ์แล้ว และได้รับการชำระเงินเรียบร้อย",
    bookingDetailTitle: "รายละเอียดการจอง",
    labelService: "บริการ:",
    labelDate: "วันที่:",
    labelTime: "เวลา:",
    labelPeople: "จำนวนคน:",
    labelPrice: "ราคารวม:",
    currency: "บาท",
    backHomeBtn: "กลับไปหน้าแรก",
    head: "Aquaventure",
    heroTitle: "ค้นพบความสนุกในทุกการผจญภัย!",
    heroDesc: "สร้างความสนุกทุกวันที่ Aquaventure — ดำน้ำ ล่องเรือ หรือขับ jetski ด้วยรอยยิ้ม!",
    heroBtn: "เริ่มการผจญภัยของคุณ",
    servicesTitle: "บริการของเรา",
    divingTitle: "ดำน้ำ",
    divingDesc: "สัมผัสโลกใต้ทะเลสุดตระการตา...",
    snorkelingTitle: "ดำน้ำตื้น",
    snorkelingDesc: "ผ่อนคลายไปกับการดำน้ำตื้นชมแนวปะการัง...",
    boatingTitle: "ล่องเรือ",
    boatingDesc: "เพลิดเพลินกับการล่องเรือ...",
    jetskiTitle: "เช่าเจ็ตสกี",
    jetskiDesc: "สนุกกับการขี่เจ็ตสกีด้วยความเร็วสุดมันส์!",
    ctaTitle: "พร้อมเริ่มผจญภัยหรือยัง?",
    ctaDesc: "ลงทะเบียนหรือล็อกอินเพื่อเริ่มต้นการผจญภัย",
    ctaBtn: "สมัครสมาชิกหรือเข้าสู่ระบบ",

    divingDetailBtn: "ดูรายละเอียด",
    snorkelingDetailBtn: "ดูรายละเอียด",
    boatingDetailBtn: "ดูรายละเอียด",
    jetskiDetailBtn: "ดูรายละเอียด", 
    titleJetski: "Jetski Ride",
    titleJetski: "ขับเจ็ทสกี",
    jetskiDesc: "สัมผัสความสนุกบนเจ็ตสกีเคลื่อนตัวไปบนผืนน้ำ พร้อมดื่มด่ำบรรยากาศของอ่าวที่งดงาม",
    
    jetskiIncludeTitle: "✅ สิ่งที่รวม:",
    jetskiInclude1: "เจ็ทสกี 1 คันต่อ 2 คน",
    jetskiInclude2: "เสื้อชูชีพ",
    jetskiInclude3: "คำแนะนำจากเจ้าหน้าที่",
    
    jetskiDurationTitle: "🕒 ระยะเวลา:",
    jetskiDuration: "1 ชั่วโมง",

    jetskiNoteTitle: "📌 หมายเหตุ:",
    jetskiNote1: "ต้องมีอายุ 15 ปีขึ้นไป",
    jetskiNote2: "สามารถขับได้โดยไม่ต้องมีใบขับขี่",

    jetskiPrice: "ราคา: ฿2,000 / ชั่วโมง",
    serviceBtn: "จองกิจกรรมนี้",
    pageTitle: "Aquaventure - การจอง",
    logoText: "Aquaventure",
    navHome: "หน้าแรก",
    navActivities: "กิจกรรม",
    bookingTitle: "จองกิจกรรมกับเรา",
    labelName: "ชื่อ - นามสกุล",
    inputName: "กรอกชื่อของคุณ",
    labelEmail: "อีเมล",
    labelActivity: "เลือกกิจกรรม",
    activityOptionDefault: "-- กรุณาเลือกกิจกรรม --",
    activityOptionScuba: "คอร์สดำน้ำ Scuba",
    activityOptionSnorkeling: "ดำน้ำตื้น",
    activityOptionBoat: "เช่าเรือส่วนตัว",
    activityOptionJetski: "ขับเจ็ทสกี",
    labelPeople: "จำนวนคน",
    inputPeople: "ระบุจำนวนคน",
    labelDate: "วันที่ต้องการจอง",
    submitBtn: "ยืนยันการจอง",
    footerTitle: "Aquaventure",
    footerDesc: "สัมผัสประสบการณ์การผจญภัยสุดพิเศษกับกิจกรรมทางทะเลที่น่าตื่นเต้น",
    footerCopyright: "© 2025 Aquaventure ทะเลผจญภัย",
    activityOptionScuba: "คอร์สดำน้ำ Scuba",          // th
    activityOptionSnorkeling: "ดำน้ำตื้น",
    activityOptionBoat: "เช่าเรือส่วนตัว",
    activityOptionJetski: "ขับเจ็ทสกี",
    labelTime: "เวลาที่ต้องการ",



  },
};

let currentLang = localStorage.getItem("language") || "th";

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem("language", lang);
  document.documentElement.lang = lang;

  for (const key in translations[lang]) {
    const element = document.getElementById(key);
    if (element) {
      const text = translations[lang][key];
      const tag = element.tagName.toLowerCase();

      if (tag === "input" || tag === "textarea") {
        element.placeholder = text;
      } else if (tag === "option") {
        element.label = text; 
        element.textContent = text; 
      } else {
        element.textContent = text;
      }
    }
  }

  const langButton = document.getElementById("langSwitch");
  if (langButton) {
    langButton.innerText = lang === "th" ? "EN" : "TH";
  }
}

function setupLanguageSwitch() {
  const langSwitchButton = document.getElementById("langSwitch");
  if (langSwitchButton) {
    langSwitchButton.addEventListener("click", () => {
      const newLang = currentLang === "th" ? "en" : "th";
      setLanguage(newLang);
    });
  }
}
window.addEventListener("load", () => {
  const defaultLang = localStorage.getItem("language") || "th";
  setLanguage(defaultLang);
  setupLanguageSwitch();
});



